### PR TITLE
Smash gg

### PR DESCRIPTION
**Pull request by BrandonCookeDev**
Just a quick try catch that encapsulates the get_matches method that is important for the main smashGG pull if there are any more updates with the api

### CODE REVIEW

**Comment by jessemtso** [comment]
this PR has too many commits, cherrypicking the latest one and comitting it manually

**Comment by BrandonCookeDev** [comment]
Yeah that was my b. Not sure how to make a PR with only a few commits but you got the only additional commit I made

**Comment by jiangtyd** [comment]
@BrandonCookeDev you can use `git rebase -i HEAD~20` (replace with whatever number) to squash commits together, and open multiple PRs with only subsets of the commits

**Comment by BrandonCookeDev** [comment]
Sounds good I'll do that from now on

**Pull request closed without merging**
