### PR TITLE
Jarrod display player region

### PR DESCRIPTION
**Pull request by JarrodBlanton**
1. Displays the player's region underneath their tag.

2. Admin functionality now allows admins to see other regions as read-only. If the admin is a super admin, they are allowed to select them. Added some additional css styling to make read-only look different.

### CODE REVIEW

**Comment by BrandonCookeDev** [comment]
changes here start at 12f4659

**Comment by jiangtyd** [comment]
can you make the base branch something less far away? o.o

**Comment by BrandonCookeDev** [comment]
I think we'd need to rebase, which I'm not super duper familiar with. 
I don't think it will be an issue after these PRs.

**Comment by BrandonCookeDev** [comment]
I'll see what I can do tho

**Comment by jiangtyd** [comment]
rebasing is easy! ish

**Comment by BrandonCookeDev** [comment]
I know you taught me a command once, it was like
```
git rebase -i HEAD~X
```
where X is the number of commits back you want your base to start... iirc

**Comment by jiangtyd** [comment]
well, you can do that to edit your commit history, roughly

I'm just really confused how this branch is based on such an old commit; shouldn't people have checked out master and developed on top of it?

**Comment by BrandonCookeDev** [comment]
Well #206 did the same thing, I think that one is because I started that branch so early then merged master into it. Idk

**Comment by jiangtyd** [comment]
oh this is a 2016 branch LOL

imo you should just create a new branch off master, and cherry-pick the commits you want onto it

**Comment by BrandonCookeDev** [comment]
Well #219 did the same thing, I think that one is because I started that branch a long time ago then merged master into it. Idk, because I made #215 recently and this did not happen.

**Comment by BrandonCookeDev** [comment]
I tried creating a new branch and then rebasing a commit range to it but that did not work. I looked at a PR for it and it had the same list of extra commits. 

After some reading, I've been trying to run something like this on another branch and I'm not getting much luck:
```
git cherry-pick 12f4659^..16eb03e
```

Thoughts?

**Comment by jiangtyd** [comment]
I feel like this should work? I'm not sure what commits you want exactly

**Comment by BrandonCookeDev** [comment]
That range in the cherry pick statement is the range that comprises the changes this or should reflect 

Maybe I'm doing something wrong? I should just be able to run this from a totally new branch off master right?

**Comment by JarrodBlanton** [comment]
Closed bad PR. New PR at #224

**Pull request closed without merging**
