### PR TITLE
Smash gg

### PR DESCRIPTION
**Pull request by BrandonCookeDev**
Fix for DQ and "CEO Bug isn't"

### CODE REVIEW

**Comment by jschnei** [comment]
Looks like there are conflicts... try merging master into this branch and recommitting.

**Comment by BrandonCookeDev** [comment]
The refactor of my module made merging an absolute disgusting bloodbath of code...
Would be nice if refactoring could be performed After functionality is achieved

**Comment by BrandonCookeDev** [comment]
PR is a wash. Replacing with #86

**Comment by jhertz** [comment]
Admins can do squash and merge, so its not an issue for a PR to have multiple commits

**Pull request closed without merging**
